### ISSUE TITLE
Update for GPU??

### ISSUE THREAD

**Issue by sushantgundla-accolite** [grohith327/simplegan#2]
Can you update the package for training the GANs on the GPU?

**Comment by grohith327** [comment]
Hello, it depends on the type of TensorFlow version you have installed. If you have installed the GPU version, the models will train on them else on the CPU. Please check if TensorFlow is using your GPU with the command `tf.test.is_gpu_available()`

**Comment by sushantgundla** [comment]
@grohith327 Thanks great! Thanks
